# Generated by Django 2.1.7 on 2019-03-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255)),
                ('date_purchase', models.DateField(verbose_name='Дата покупки')),
                ('country_origin', models.CharField(max_length=255, verbose_name='Страна производства')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('size_height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('size_width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('size_length', models.IntegerField(blank=True, null=True, verbose_name='Длина')),
                ('size_diameter', models.IntegerField(blank=True, null=True, verbose_name='Диаметр')),
                ('style', models.CharField(blank=True, max_length=255, verbose_name='Стиль')),
                ('period', models.CharField(max_length=255, verbose_name='Период')),
                ('condition', models.CharField(blank=True, max_length=255, verbose_name='Состояние товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('city_purchase', models.CharField(max_length=255, verbose_name='Город покупки')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес')),
                ('price_purchase', models.IntegerField(verbose_name='Цена покупки, €')),
                ('price_purchase_rub', models.IntegerField(blank=True, null=True)),
                ('additional_expenses', models.IntegerField(blank=True, default=0, verbose_name='Дополнительные расходы')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Курс обмена')),
                ('price_selling', models.IntegerField(verbose_name='Цена продажи, ₽')),
                ('client', models.TextField(blank=True, verbose_name='Данные покупателя')),
                ('sum_prepayment', models.IntegerField(blank=True, null=True, verbose_name='Сумма предоплаты')),
                ('date_prepayment', models.DateField(blank=True, null=True, verbose_name='Дата предоплаты')),
                ('date_delivery', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('sold', models.BooleanField(verbose_name='Товар продан')),
                ('publish', models.BooleanField(verbose_name='Опубликовать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория')),
            ],
        ),
    ]
